"""Run materialized GenX cases locally with Julia + Gurobi, one after another.

The shipped `jobscript.sh` targets SLURM on Berkeley Savio and hard-codes a
cluster project path, so it cannot be used locally.  This driver invokes
`julia --project=<env> Run.jl` in each case directory instead, logs stdout and
the wall time, and skips cases that already have results.

Each case is a 168-hour, 8,870-zone, 2,171-resource unit-commitment DC-OPF, so
budget tens of minutes and several GB of RAM per case.  Solves run strictly one
at a time; to use more of the machine, launch several terminals against
different `--runs`.

Note on scope: demand varies only by SEASON (4 distinct files), and the 7
weather years within a season change only `Generators_variability.csv`.  Running
all 28 cases per allocation therefore gives 7 replicates per season -- a
sampling distribution over renewable conditions -- rather than 28 independent
tests of load placement.  `--cases p1,p8,p15,p22` is the one-per-season subset
if a smaller run is wanted.

Prerequisites (one time):
    julia -e 'using Pkg; Pkg.add(["GenX", "Gurobi"])'
  Gurobi must already be licensed (`gurobi_cl --license`).

CLI parameters
  --runs        comma-separated run tags under --root (default: all present)
  --cases       comma-separated cases (default: all 28)
  --project     Julia project/environment for the GenX install (default: the
                active default environment)
  --julia       julia executable (default: julia)
  --threads     Julia threads (default 0 = leave to Julia)
  --timeout     per-case seconds before giving up (default 21600 = 6 h)
  --force       re-run cases that already have a results folder
  --dry-run     print what would run, then exit
  --root        default genx/scenarios_rescaled
  --emit-slurm  write a SLURM array submission script for the same job list and
                exit without solving anything (for later cluster access)
  --slurm-account/--slurm-partition/--slurm-time/--slurm-cpus/--slurm-project
                SLURM header values, defaulting to the shipped jobscript.sh

Outputs
  <case>/results/           GenX's own output (written by GenX)
  <case>/run_local.log      stdout+stderr of that case's solve
  data/checks/genx_rescale/local_run_log.csv   per case: status, seconds
  <root>/submit_genx.sh + genx_cases.txt       with --emit-slurm

Usage
  python scripts/load_projection/genx/run_genx_local.py --dry-run
  python scripts/load_projection/genx/run_genx_local.py --runs genx__control --cases p1
  python scripts/load_projection/genx/run_genx_local.py
  python scripts/load_projection/genx/run_genx_local.py --emit-slurm --slurm-project /global/scratch/users/me/GenX.jl
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "scripts/load_projection/genx"))
from genx_demand_io import GENX_ROOT, scenario_seasons  # noqa: E402

DEFAULT_ROOT = GENX_ROOT / "scenarios_rescaled"
LOG_DIR = ROOT / "data/checks/genx_rescale"
# Default case set: weather years 2011 (highest VRE availability) and 2012
# (lowest), across all four seasons -- 8 of the 28 cases. The weather year
# changes only Generators_variability.csv, so two years bracketing the
# renewable range is a replicate pair, not a loss of load-allocation signal.
DEFAULT_CASES = "p5,p6,p12,p13,p19,p20,p26,p27"
SEASON_CASES = "p1,p8,p15,p22"      # one per season, all 7 years dropped


def has_results(case_dir: Path) -> bool:
    return any((case_dir / n).exists() for n in ("results", "Results"))


SLURM_TEMPLATE = """#!/bin/bash
# GenX case sweep as a SLURM job array -- generated by run_genx_local.py.
# One array task per case; the case list is genx_cases.txt beside this script.
#
#   sbatch --array=1-{n} submit_genx.sh
#
#SBATCH --job-name=genx_sweep
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --cpus-per-task={cpus}
#SBATCH --time={time}
#SBATCH --output=slurm_logs/genx_%A_%a.out
#SBATCH --error=slurm_logs/genx_%A_%a.err

module load julia
module load gurobi

CASE=$(sed -n "${{SLURM_ARRAY_TASK_ID}}p" "$(dirname "$0")/genx_cases.txt")
if [ -z "$CASE" ]; then echo "no case for task ${{SLURM_ARRAY_TASK_ID}}"; exit 1; fi
echo "task ${{SLURM_ARRAY_TASK_ID}}: $CASE"
cd "$CASE" || exit 1
julia --project="{project}" Run.jl
"""


def emit_slurm(root: Path, jobs, args) -> None:
    """Write a job-array script covering the same case list the local run would."""
    listing = root / "genx_cases.txt"
    listing.write_text(
        "\n".join(str((root / r / c).resolve()) for r, c in jobs) + "\n",
        encoding="utf-8")
    script = root / "submit_genx.sh"
    script.write_text(SLURM_TEMPLATE.format(
        n=len(jobs), account=args.slurm_account, partition=args.slurm_partition,
        cpus=args.slurm_cpus, time=args.slurm_time, project=args.slurm_project),
        encoding="utf-8")
    (root / "slurm_logs").mkdir(exist_ok=True)
    print(f"wrote {listing} ({len(jobs)} cases)")
    print(f"wrote {script}")
    print(f"\nOn the cluster:\n  sbatch --array=1-{len(jobs)} {script.name}")
    print("Adjust --slurm-project to the GenX.jl environment on that machine; the "
          "paths in genx_cases.txt are absolute and must be valid there.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--runs", default=None)
    ap.add_argument("--cases", default=None,
                    help="default: " + DEFAULT_CASES + " (2 weather years x 4 seasons); pass a comma list or use tree.cases for all 28")
    ap.add_argument("--project", default=None)
    ap.add_argument("--julia", default="julia")
    ap.add_argument("--threads", type=int, default=0)
    ap.add_argument("--timeout", type=int, default=21600)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--root", default=str(DEFAULT_ROOT))
    ap.add_argument("--emit-slurm", action="store_true")
    ap.add_argument("--slurm-account", default="fc_emac")
    ap.add_argument("--slurm-partition", default="savio3")
    ap.add_argument("--slurm-cpus", type=int, default=12)
    ap.add_argument("--slurm-time", default="24:00:00")
    ap.add_argument("--slurm-project", default="/global/scratch/users/manocha/GenX.jl")
    args = ap.parse_args()

    root = Path(args.root)
    if not root.exists():
        sys.exit(f"{root} not found -- materialize runs first "
                 f"(materialize_genx_cases.py --run-tag <tag> --enable-outputs)")
    # a run folder is one that actually holds case directories; this keeps
    # bookkeeping folders (slurm_logs) from being mistaken for allocations.
    # Checking for p1 specifically broke when the case set dropped p1.
    available = sorted(p.name for p in root.iterdir()
                       if p.is_dir() and any(c.is_dir() and c.name.startswith("p")
                                             and c.name[1:].isdigit()
                                             for c in p.iterdir()))
    runs = args.runs.split(",") if args.runs else available
    unknown = [r for r in runs if r not in available]
    if unknown:
        sys.exit(f"unknown run tag(s) {unknown}; available: {available}")

    tree = scenario_seasons()
    cases = args.cases.split(",") if args.cases else DEFAULT_CASES.split(",")
    bad = [c for c in cases if c not in tree.case_season]
    if bad:
        sys.exit(f"unknown case(s) {bad}")

    jobs = [(r, c) for r in runs for c in cases]
    print(f"{len(jobs)} case-solves: {len(runs)} run(s) x {len(cases)} case(s)")
    for r in runs:
        print(f"  {r}")
    print(f"  cases: {', '.join(f'{c} ({tree.case_season[c]})' for c in cases)}")

    cmd_base = [args.julia]
    if args.project:
        cmd_base.append(f"--project={args.project}")
    if args.threads:
        cmd_base.append(f"--threads={args.threads}")
    cmd_base.append("Run.jl")
    print(f"  command per case: {' '.join(cmd_base)}\n")

    if args.emit_slurm:
        emit_slurm(root, jobs, args)
        return

    if args.dry_run:
        for r, c in jobs:
            state = "SKIP (has results)" if has_results(root / r / c) and not args.force else "run"
            print(f"  {state:20s} {r}/{c}")
        return

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    rows = []
    for i, (r, c) in enumerate(jobs, 1):
        case_dir = root / r / c
        if has_results(case_dir) and not args.force:
            print(f"[{i}/{len(jobs)}] skip {r}/{c} (results exist; --force to redo)")
            rows.append({"run": r, "case": c, "status": "skipped", "seconds": 0.0})
            continue
        print(f"[{i}/{len(jobs)}] {r}/{c} ... ", end="", flush=True)
        t0 = time.time()
        log = case_dir / "run_local.log"
        try:
            with open(log, "w", encoding="utf-8") as fh:
                p = subprocess.run(cmd_base, cwd=case_dir, stdout=fh,
                                   stderr=subprocess.STDOUT, timeout=args.timeout)
            dt = time.time() - t0
            ok = p.returncode == 0 and has_results(case_dir)
            status = "ok" if ok else f"failed(rc={p.returncode})"
        except subprocess.TimeoutExpired:
            dt, status = time.time() - t0, "timeout"
        print(f"{status} in {dt/60:.1f} min  (log: {log.name})")
        rows.append({"run": r, "case": c, "status": status, "seconds": round(dt, 1)})

    out = LOG_DIR / "local_run_log.csv"
    df = pd.DataFrame(rows)
    if out.exists():
        df = pd.concat([pd.read_csv(out), df], ignore_index=True)
    df.to_csv(out, index=False)
    n_ok = (pd.DataFrame(rows).status == "ok").sum()
    print(f"\n{n_ok}/{len(jobs)} succeeded; wrote {out.relative_to(ROOT)}")
    if n_ok < len(jobs):
        print("Inspect a failing case's run_local.log for the Julia/Gurobi error.")


if __name__ == "__main__":
    main()
